$(document).ready(function(){
    $('.food-slider').slick({
        autoplay:true,
        slidesToShow:3,
        slidesToShow:1,
        prevArrow:"prev-btn",
        nextArrow:"next-btn"
    });
});